version: '3.1'

services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      TZ: "Europe/Paris"
    ports:
      - '5432:5432'
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: on-failure:10

